docs: add cloud install
horizoncd/horizoncd.github.io pull request #19
Opened 2023-03-28 07:51 UTC by kilosonc

2023-03-30 02:32 UTC, iamyeka requested changes

2023-03-30 02:32 UTC, iamyeka commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +title: Local Installation
Local is not right.

2023-03-30 02:32 UTC, iamyeka commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +Installing by script is not recommended in production environment. We well install Horizon manually in this tutorial.
will install

2023-03-30 02:32 UTC, iamyeka commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +4. Check if these's a ingress controller in your cluster. If not, you should install one. Please refer to [Ingress Controller Installation](https://kubernetes.github.io/ingress-nginx/deploy) for more
there's an ingress

2023-03-30 02:32 UTC, iamyeka commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +The bundled Harbor uses a self-signed certificate. When Kubernetes runtime tries to pull the image from the registry service, it will fail because of the certificate. So you should tells the runtime
should tell

2023-03-30 02:32 UTC, iamyeka commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +# helm install horizon horizon/horizon --namespace horizoncd --create-namespace --set tags.minimal=false,tags.full=true \
'#' need to be remove, otherwise codes users copy from here cannot be run successfully.

2023-03-30 02:32 UTC, iamyeka commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +If your cluster couldn't access docker hub, you should use our mirror registry to pull the images.
Maybe put this line in Line39?

2023-03-30 02:32 UTC, iamyeka commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +If you are using `CoreDNS` as the DNS server, you can edit the `resolv.conf` file of the `coredns` pod to add the registry service's domain name for all kubernetes nodes.
Whose resolv.conf? nodes or coredns pod?

2023-03-30 02:32 UTC, iamyeka commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +##### Containerd
What about cri-o? Has it been set as another choice for users to chose on Cloud Provider?

2023-03-30 02:32 UTC, iamyeka commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +# helm install horizon horizon/horizon --namespace horizoncd --create-namespace --set tags.minimal=false,tags.full=true \
And you should move this up a little bit. Or you may use `helm upgrade` because users could have installed a release before reading these info.

2023-03-30 02:32 UTC, iamyeka commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +The `tags.minimal` and `tags.full` are used to control which components will be installed. In production environment, installing all components is recommended. So you should set `tags.minimal=false`
Typically Gitlab and Mysql are deployed out of the K8s, you may need to point it out and tell them how to set self-defined Gitlab and Mysql just like the gudelines of `Local installation`.

2023-03-30 02:43 UTC, xuzhu-591 commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +title: Local Installation
local ?

2023-03-30 02:43 UTC, xuzhu-591 commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +Installing by script is not recommended in production environment. We well install Horizon manually in this tutorial.
well -> will

2023-03-30 02:43 UTC, xuzhu-591 commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +helm repo add horizon https://openhorizon.github.io/helm-charts
```bash
helm repo add horizoncd https://horizoncd.github.io/helm-charts
```

prefer to name the repo `horizoncd` ?

2023-03-30 02:43 UTC, xuzhu-591 commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +helm install horizon horizon/horizon --namespace horizoncd --create-namespace --set tags.minimal=false,tags.full=true
horizoncd/horizon

2023-03-30 02:43 UTC, xuzhu-591 commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +If your cluster couldn't access docker hub, you should use our mirror registry to pull the images.
should -> can/could ?

2023-03-30 02:43 UTC, xuzhu-591 commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +DNS_IP=kubectl get service -n kube-system kube-dns -o jsonpath='{.spec.clusterIP}'
DNS_IP=$()

2023-03-30 02:43 UTC, xuzhu-591 commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +DNS_IP=kubectl get service -n kube-system kube-dns -o jsonpath='{.spec.clusterIP}'
DNS_IP=$()

2023-03-30 02:43 UTC, xuzhu-591 commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +SVC_IP=kubectl get services -n horizoncd horizon-registry -ojsonpath="{.spec.clusterIP}"
miss command substitution

2023-03-30 03:20 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +title: Local Installation
fixed

2023-03-30 03:20 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +title: Local Installation
fixed

2023-03-30 03:21 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +4. Check if these's a ingress controller in your cluster. If not, you should install one. Please refer to [Ingress Controller Installation](https://kubernetes.github.io/ingress-nginx/deploy) for more
fixed

2023-03-30 03:21 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +Installing by script is not recommended in production environment. We well install Horizon manually in this tutorial.
fixed

2023-03-30 03:21 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +Installing by script is not recommended in production environment. We well install Horizon manually in this tutorial.
fixed

2023-03-30 03:22 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +helm repo add horizon https://openhorizon.github.io/helm-charts
fixed

2023-03-30 03:22 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +helm install horizon horizon/horizon --namespace horizoncd --create-namespace --set tags.minimal=false,tags.full=true
fxied

2023-03-30 03:32 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +The `tags.minimal` and `tags.full` are used to control which components will be installed. In production environment, installing all components is recommended. So you should set `tags.minimal=false`
fixed

2023-03-30 03:34 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +If your cluster couldn't access docker hub, you should use our mirror registry to pull the images.
fixed

2023-03-30 03:35 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +If your cluster couldn't access docker hub, you should use our mirror registry to pull the images.
fixed

2023-03-30 03:41 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +If you are using `CoreDNS` as the DNS server, you can edit the `resolv.conf` file of the `coredns` pod to add the registry service's domain name for all kubernetes nodes.
said `On Kubernetes Nodes`

2023-03-30 03:44 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +SVC_IP=kubectl get services -n horizoncd horizon-registry -ojsonpath="{.spec.clusterIP}"
fixed

2023-03-30 03:45 UTC, kilosonc commented on docs/tutorials/how-to-install/cloud-provider-installation.md
> +The bundled Harbor uses a self-signed certificate. When Kubernetes runtime tries to pull the image from the registry service, it will fail because of the certificate. So you should tells the runtime
said

2023-03-31 02:40 UTC, iamyeka approved these changes

2023-03-31 10:17 UTC, xuzhu-591 approved these changes

2023-03-31 10:17 UTC, merged